outline_config:
  max_new_tokens: 3000
  temperature: 0.9
  top_p: 0.9

character_config:
  max_new_tokens: 3000
  temperature: 0.4
  top_p: 0.9

writer_config:
  max_new_tokens: 4096
  temperature: 0.4
  top_p: 0.9

reflect_config:
  max_new_tokens: 3000
  temperature: 0.4
  top_p: 0.9



